# Generated by Django 4.1.7 on 2023-04-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Виды')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bruschatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Характеристики')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('price', models.PositiveIntegerField(default=True, verbose_name='Цена')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bruschatka.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Тротуарная плитка брусчатка',
                'verbose_name_plural': 'Тротуарная плитка брусчатка',
                'ordering': ['cat_id', 'title'],
            },
        ),
    ]
